on: [pull_request]
name: Benchmark pull requests
jobs:
  runBenchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: boa-dev/criterion-compare-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
